# Generated by Django 4.0.4 on 2022-04-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3link', models.TextField()),
                ('captions_user', models.TextField()),
                ('audio_text', models.TextField()),
            ],
        ),
    ]
